apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: frontend                                  
    spec:
      containers:
        - image: tx640/hw5_front:v2
          imagePullPolicy: Always                         
          name: frontend
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service              
metadata:
  name: front-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: frontend
    
