apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: tx640/hw5_front:v1
      name: sa-frontend
      ports:
        - containerPort: 80
