apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: rinormaloku/sentiment-analysis-web-app
        imagePullPolicy: Always
        name: web
        env:
          - name: SA_LOGIC_API_URL
            value: "http://logic"
        ports:
          - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: web_serv
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web

